apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
  selector:
    app: sample-app
